=== FirelightFlagboy/gh-actions-workflows-docker-services/pkg-info.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "pkg-info",
  "description": "A package information descriptor.",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "arch_asset_patterns": {
      "description": "Github asset patterns",
      "type": "object",
      "propertyNames": {
        "$ref": "#/definitions/arch"
      },
      "additionalProperties": {
        "$ref": "#/definitions/regex"
      }
    },
    "command": {
      "type": "string"
    },
    "document-url": {
      "$ref": "#/definitions/url"
    },
    "latest_version": {
      "type": "string"
    },
    "mode": {
      "type": "string",
      "enum": [
        "github-release",
        "bash-command",
        "jq-script"
      ]
    },
    "name": {
      "type": "string"
    },
    "repository_path": {
      "description": "Github mode repository path",
      "type": "string",
      "pattern": "^[\\w-]+/[\\w-]+$",
      "examples": [
        "gohugoio/hugo"
      ]
    },
    "script-path": {
      "$ref": "#/definitions/path"
    },
    "versions": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "propertyNames": {
          "$ref": "#/definitions/arch"
        },
        "additionalProperties": {
          "type": "object",
          "properties": {
            "digest": {
              "$ref": "#/definitions/digest"
            },
            "download_url": {
              "$ref": "#/definitions/url"
            },
            "filename": {
              "$ref": "#/definitions/path"
            }
          },
          "required": [
            "filename",
            "download_url",
            "digest"
          ],
          "additionalProperties": false
        }
      }
    }
  },
  "if": {
    "properties": {
      "mode": {
        "const": "github-release"
      }
    }
  },
  "then": {
    "required": [
      "repository_path",
      "arch_asset_patterns"
    ]
  },
  "else": {
    "if": {
      "properties": {
        "mode": {
          "const": "bash-command"
        }
      }
    },
    "then": {
      "required": [
        "command"
      ]
    }
  },
  "required": [
    "name",
    "mode"
  ],
  "definitions": {
    "arch": {
      "type": "string",
      "enum": [
        "arm64",
        "amd64"
      ]
    },
    "digest": {
      "type": "string",
      "oneOf": [
        {
          "pattern": "^sha256:[0-9a-f]{64}$"
        },
        {
          "pattern": "^sha512:[0-9a-f]{128}$"
        }
      ]
    },
    "path": {
      "type": "string",
      "format": "path"
    },
    "regex": {
      "type": "string",
      "format": "regex"
    },
    "url": {
      "type": "string",
      "format": "uri"
    }
  },
  "additionalProperties": false
}

=== FirelightFlagboy/gh-actions-workflows-docker-services/pkg-info.json
{
  "$schema": "./pkg-info.schema.json",
  "name": "Pkg Updater",
  "latest_version": "0.0.2",
  "versions": {
    "0.0.2": {
      "amd64": {
        "filename": "pkg-info-update-linux-amd64",
        "download_url": "https://github.com/FirelightFlagboy/gh-actions-workflows-docker-services/releases/download/v0.0.2/pkg-info-updater-linux-amd64",
        "digest": "sha512:14fd6039bfb4fb3dac779811b97bb4fea5ac80264cecb09dfef79f9418bcc261682348c3aacb5f8324545407fc6c212d32452bd24b592d5524c0f58836c7b5ee"
      }
    }
  },
  "mode": "github-release",
  "arch_asset_patterns": {
    "amd64": "^.*-linux-amd64$"
  }
}

=== FirelightFlagboy/gh-actions-workflows-docker-services/tests/samples/single-version-github-release.json
{
  "$schema": "../../pkg-info.schema.json",
  "name": "Gohugo",
  "latest_version": "v0.119.0",
  "versions": {
    "v0.119.0": {
      "amd64": {
        "filename": "hugo_0.119.0_linux-amd64.tar.gz",
        "download_url": "https://github.com/gohugoio/hugo/releases/download/v0.119.0/hugo_0.119.0_linux-amd64.tar.gz",
        "digest": "sha512:01781c4162da4788a98b5d704222ca007ad020dbe3dfbdc18858ee2eafa115ba2792593370a905aa7c8f2a9f07170721f2de44fca191b29dc01f1108ea1af631"
      },
      "arm64": {
        "filename": "hugo_0.119.0_linux-arm64.tar.gz",
        "download_url": "https://github.com/gohugoio/hugo/releases/download/v0.119.0/hugo_0.119.0_linux-arm64.tar.gz",
        "digest": "sha512:18db0f2d55ec94eb8555af16964d40863c60aaa89498a45d50c4644cc9b018a46744a323d1ce7f4af59b0c0bd665a97d5b212c231f7f368e3ac5ac81aa9a55ec"
      }
    }
  },
  "mode": "github-release",
  "repository_path": "gohugoio/hugo",
  "arch_asset_patterns": {
    "amd64": "^hugo_([0-9]+(\\.[0-9]+)+)_linux-amd64.tar.gz$",
    "arm64": "^hugo_([0-9]+(\\.[0-9]+)+)_linux-arm64.tar.gz$"
  }
}
